# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
# created-by: conda 24.11.3
# command: conda list --explicit > environment2.yml
# --explicit导出的也是不完整的，只包括用conda install的包
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2025.7.15-haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ucrt-10.0.22621.0-haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/vc14_runtime-14.44.35208-h4927774_10.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.3-h2df5915_10.conda
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.44.35208-ha6b5a95_10.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2023.1.0-h59b6b97_46320.conda
https://repo.anaconda.com/pkgs/main/win-64/libffi-3.4.4-hd77b12b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-3.0.17-h35632f6_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.50.2-hda9a48d_1.conda
https://repo.anaconda.com/pkgs/main/win-64/tbb-2021.8.0-h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-2023.1.0-h6b88ed4_46358.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.8.20-h8205438_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py38h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-75.1.0-py38haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.44.0-py38haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.24.3-py38h8a87ada_1.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-24.2-py38haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.8-py38h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.4-py38h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.24.3-py38h79a8e48_1.conda
