# 最佳实践
# command: conda env export --no-builds > environment_nob.yml
name: envtest
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - ca-certificates=2025.7.15
  - intel-openmp=2023.1.0
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openssl=3.0.17
  - pip=24.2
  - python=3.8.20
  - setuptools=75.1.0
  - sqlite=3.50.2
  - tbb=2021.8.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.44.0
  - pip:
      - colorama==0.4.6
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - importlib-resources==6.4.5
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - packaging==25.0
      - pandas==2.0.3
      - pillow==10.4.0
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - seaborn==0.13.2
      - six==1.17.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - zipp==3.20.2
# prefix: C:\Users\Cavendishes\.conda\envs\envtest2 记得手动删除最后这个prefix
